name: Deploy Angular App

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Build do Projeto
        run: npm run build -- --configuration=production --base-href=/dog-app/

      - name: Implantação (Deploy)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/dogs/browser
          branch: gh-pages